mode:
  production

production:
  datasources:
    mysql:
      host: MYSQL_HOST
      port: 3306
      database: mlsql_cluster
      username: root
      password: mlsql
      initialSize: 3
      disable: false
    mongodb:
      disable: true
    redis:
      disable: true

test:
  datasources:
    mysql:
      disable: true
    mongodb:
      disable: true

application:
  controller: tech.mlsql.cluster.controller
  model: tech.mlsql.cluster.model
  util:
  test:
  static:
    enable: true
  template:
    engine:
      enable: true

serviceframework:
  template:
    loader:
      classpath:
        enable: true
  static:
    loader:
      classpath:
        enable: true
        dir: "streamingpro/assets"
###############http config##################
http:
  disable: false
  host: 0.0.0.0
  port: 8080
  client:
    accept:
      timeout: 43200000

thrift:
  disable: true
dubbo:
  disable: true



